### ISSUE TITLE
ModuleNotFoundError: No module named 'striped_smith_waterman'

### ISSUE THREAD

**Issue by mcolic** [petrov-lab/tuba-seq#1]
Hi,

I am trying to run the preprocess.py file, however, I keep getting the error that there is no module name 'striped_smith_waterman'? I have successfully installed the Complete-Striped-Smith-Waterman-Library, but not sure what the problem is. I would greatly appreciate it if you could assist with this.

Thank you.
Medina

**Comment by cd-mcfarland** [comment]
Hi Medina, 

This library is a _submodule_ within the repo, which requires the `--recursive` keyword argument when cloning, e.g.  
```git clone --recursive https://github.com/petrov-lab/tuba-seq.git ```
Be sure to 'build' this C library using the 'make' command, as described in the Install Instructions. 

Also, please note that this library is intended for Single-End Illumina reads. We recommend using Paired-End (PE) sequencing now. I can host software intended for PE reads, if you would like, although I would recommend accessing our tumor calls directly on GEO if you are using published data from the Petrov/Winslow labs. 

Bests,
Chris

**Comment by mcolic** [comment]
Hi Chris,

Thanks for getting back my question.
Yes, I have done it that way - however, I keep getting errors with it; either no module names striped_smith_waterman or libssw.so does not exist in PATH (even after I copy it to the tuba_seq folder).

Yes, we have used the paired-end sequencing, and are using the merged reads for downstream analysis.
Thanks,
Medina

**Comment by cd-mcfarland** [comment]
Hi Medina, 

Your system's ```PATH``` is an _Environment Variable_, which is a parameter specific to your programming setup or 'environment' and hard for me to troubleshoot without knowing more about your setup (you can learn more here: https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them).

**Comment by cd-mcfarland** [comment]
Also, you shouldn't need to copy over any files. I'd go into the sub-module and see if it installs fine, as suggested by their Install README. My _guess_ is that there is something unique about your compiler setup. Also, we _say_ it should work with gcc or clang, but 90% of the unit testing is in gcc.

**Comment by mcolic** [comment]
Yep, resolved it. Thank you!
